# Host to use for canonical URL generation (without trailing slash)
host: n/a

# Header-related options
show_govuk_logo: true
# service_name:
# service_link: https://www.larry-the-cat.service.gov.uk

# Links to show on right-hand-side of header
# header_links:
#   About: /
